### ISSUE TITLE
ObjectCopier ist not working as expected

### ISSUE THREAD

**Issue by margrie91-69** [eclipse-serializer/serializer#150]
## Environment Details
* Eclipse Serializer Version: 2.0.0
* JDK version: 21
* OS: WSL
* Used frameworks: JUnit, AssertJ

## Describe the bug
I wrote a little Testcase and I think this might be a bug in the ObjectCopier class.

```
@Test
public void copyList() {
     List<String> list = List.of("Test");

     try (var copier = ObjectCopier.New()) {
          Assertions.assertThat(copier.copy(list)).hasSize(1);
     }
}
```

I see this error message:

`java.lang.AssertionError: 
Expected size: 1 but was: 2 in:
["Test", java.lang.Object@13d186db]`

## To Reproduce
Just run the above mentioned testcase.

## Expected behavior
The List is copied, and there is no additional nonsense value in it

## Screenshots
-

## Additional context
This currently prevents me from using EclipseStore in a project.
I want to use the ObjectCopier to deal with concurrency issues that might otherwise occur. (Create a Repository layer in Spring, and only return copies of objects)
I am open for workarounds.

**Comment by zdenek-jonas** [comment]
For immutable collections, a special type handler must be used:
https://docs.eclipsestore.io/manual/storage/addendum/specialized-type-handlers.html#jdk17

**Comment by margrie91-69** [comment]
Ah alright, sorry I missed this in the doc.
I am using the spring boot integration currently, so these type handlers are already registerted for the StorageFoundation there.
Is there any change to get an ObjectCopier instance that has the same configuration somehow?

**Comment by zdenek-jonas** [comment]
try:

```java
    @Test
    public void copyList() {
        List<String> list = List.of("Test");

        SerializerFoundation<?> foundation = SerializerFoundation.New();
        BinaryHandlersJDK17.registerJDK17TypeHandlers(foundation);

        try (var copier = ObjectCopier.New(foundation)) {
            Assertions.assertThat(copier.copy(list)).hasSize(1);
        }
    }
```
