### ISSUE TITLE
Documentation not generating

### ISSUE THREAD

**Issue by JOpsDev** [eclipse-serializer/serializer#18]
Readme states:

> Build only the documentation PDF
> 
> mvn generate-resources -pl :documentation

But I get 

```
mvn generate-resources -pl :documentation
[INFO] Scanning for projects...
[ERROR] [ERROR] Could not find the selected project in the reactor: :documentation @ 
[ERROR] Could not find the selected project in the reactor: :documentation -> [Help 1]
```

Also I could not find any PDF generated. Does the Readme need a correction?

**Comment by fh-ms** [comment]
The updated online docs will be available at https://docs.eclipsestore.io with the release next week.
