### ISSUE TITLE
Java 22 from EA 16 - unsafe.ensureClassInitialized(Class) has been removed

### ISSUE THREAD

**Issue by zdenek-jonas** [eclipse-serializer/serializer#69]
According to the Document: https://jdk.java.net/22/release-notes
There are some changes in unsafe.java

> sun.misc.Unsafe shouldBeInitialized and ensureClassInitialized are removed ([JDK-8316160](https://bugs.openjdk.org/browse/JDK-8316160))
> 
> core-libs
> 
> The shouldBeInitialized(Class) and ensureClassInitialized(Class) methods have been removed from sun.misc.Unsafe. These methods have been deprecated for removal since JDK 15. java.lang.invoke.MethodHandles.Lookup.ensureInitialized(Class) was added in Java 15 as a standard API to ensure that an accessible class is initialized.

The Eclipse Store uses this Method in class: XMemory.java

It is important to resolve this issue for the functionality of eclipse-serializer for java 22 and above

**Comment by hg-ms** [comment]
To distinguish between different VM versions the VmChecks in XMemory.java could be extended to setup VM specific MemoryAccessors.
Replacing ensureClassInitialized with Lookup.ensureInitialized should be possible,
shouldBeInitialized is not used.
The MemoryAccessorGeneric which is used when running on Android or GraalVM does not use the removed ensureClassInitialized call.
